# Generated by Django 3.1.7 on 2021-03-25 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_item', to='finance.accounttype')),
            ],
        ),
        migrations.CreateModel(
            name='AccountYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_debit', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='Total Debit')),
                ('total_credit', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='Total Credit')),
                ('balance', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='Balance')),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.accounttype')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trnsaction_type', models.CharField(blank=True, choices=[('General', 'General'), ('POS', 'POS')], max_length=32)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('ref_no', models.CharField(blank=True, max_length=255, null=True)),
                ('voucher_no', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('post_status', models.CharField(blank=True, choices=[('pending', 'pending'), ('posted', 'posted')], max_length=32)),
                ('account_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.accountyear')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('vat', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='vat(%)')),
                ('tax', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='tax(%)')),
                ('debit', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='Debit')),
                ('credit', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='Credit')),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.ledger')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(blank=True, max_length=255, null=True)),
                ('debit', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='Debit')),
                ('credit', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='Credit')),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.transaction')),
            ],
        ),
    ]
