# Generated by Django 3.1.7 on 2021-03-23 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('home_district', models.CharField(blank=True, max_length=255, null=True)),
                ('spouse_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('religion', models.CharField(blank=True, max_length=255, null=True)),
                ('date_joining', models.DateField(blank=True, null=True)),
                ('entry_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_scale', models.CharField(blank=True, max_length=255, null=True)),
                ('picture', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
                ('archive_status', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=32)),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], max_length=32)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
