# Generated by Django 3.1.7 on 2021-03-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='date_joining',
            new_name='date_joined',
        ),
    ]
